Submitted batch job 22210273
Begin global sampling, round  0 ...
Create sample set...
Submit jobs to CASM...
['cd job_$SLURM_ARRAY_TASK_ID', 'python -u /expanse/lustre/scratch/jholber/temp_project/active-learning/data_generation_surrogate_temp.py monte_settings_$SLURM_ARRAY_TASK_ID.json ', 'cd ../']
Compile output...
