#!/bin/bash
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=10
#SBATCH --mem=20G
#SBATCH -t 4:00:00
#SBATCH -J monte
#SBATCH -A mia346
#SBATCH -o output-%j.e
#SBATCH -e errors-%j.e
#SBATCH --export=ALL
#SBATCH --mail-type=ALL
#SBATCH --mail-user=holber@umich.edu

python train_simple.py