#!/bin/bash
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=20G
#SBATCH -t 4:00:00
#SBATCH -J active_learning
#SBATCH -A mia341 
#SBATCH -o outputFiles/output-%j.e
#SBATCH -e outputFiles/errors-%j.e
#SBATCH --export=ALL
#SBATCH --mail-type=ALL
#SBATCH --mail-user=holber@umich.edu

# module reset

# '/cm/shared/apps/spack/gpu/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/anaconda3-2020.11-bsn4npoxyw7jzz7fajncek3bvdoaa5wv/bin/conda'
# conda init bash
# conda activate

python -u main.py LCO_casm.ini 